module.exports = {
    CONNECT: 'CONNECT',
    START_RECORDING: 'START_RECORDING',
    RECONNECT: 'RECONNECT',
    RECOVER: 'RECOVER',
    CONTINUE: 'CONTINUE',
    WAIT_BATTLE: 'WAIT_BATTLE',
    WAIT_OPPONENT: 'WAIT_OPPONENT',
    GET_BATTLE_INFO: 'GET_BATTLE_INFO',

    GET_READY_FRIST_DANCER: 'GET_READY_FRIST_DANCER',
    START_FRIST_DANCER: 'START_FRIST_DANCER',

    GET_READY_SECOND_DANCER: 'GET_READY_SECOND_DANCER',
    START_SECOND_DANCER: 'START_SECOND_DANCER',

    FINISH_BATTLE: 'FINISH_BATTLE',

    USER_DISCONNECT: 'USER_DISCONNECT',
    USERID_DUPLICATED: 'USERID_DUPLICATED',
    OPPONENT_DISCONNECTED: 'OPPONENT_DISCONNECTED',
    QUIT: 'QUIT',
    QUIT_SUCCESS: 'QUIT_SUCCESS',
};