module.exports = {
    CONNECT: 'CONNECT',
    RECOVER: 'RECOVER',
    CONTINUE: 'CONTINUE',
    WAIT_BATTLE: 'WAIT_BATTLE',
    WAIT_OPPONENT: 'WAIT_OPPONENT',
    GET_BATTLE_INFO: 'GET_BATTLE_INFO',
    USER_DISCONNECT: 'USER_DISCONNECT',
    USERID_DUPLICATED: 'USERID_DUPLICATED',
    OPPONENT_DISCONNECTED: 'OPPONENT_DISCONNECTED',
    QUIT: 'QUIT',
    QUIT_SUCCESS: 'QUIT_SUCCESS',
};