module.exports = {
    CONNECT_SUCCESS: 'CONNECT_SUCCESS',
    WAIT_BATTLE: 'WAIT_BATTLE',
    USERID_DUPLICATED: 'USERID_DUPLICATED',
    OPPONENT_DISCONNECTED: 'OPPONENT_DISCONNECTED',
    QUIT: 'QUIT',
    QUIT_SUCCESS: 'QUIT_SUCCESS',
    CONTINUE: 'CONTINUE',
    RECOVER: 'RECOVER',
    CONNECT: 'CONNECT',
};